-----BEGIN ENCRYPTED PRIVATE KEY-----
MGcwGwYJKoZIhvcNAQUDMA4ECGqM8Yjy43GRAgIIAARIqm9yaxWZ0CcfTNz34kaz
KnAVfPMi9vCREUkHa/0BoDJ7GjYEgBU01LFUJrg1/g1c3whFkYbF51XdfXkCxMxj
4WYqDpSYyoWW
-----END ENCRYPTED PRIVATE KEY-----
